#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
#@
#@ #! Store some default variables to make things cleaner below
#@ cluster_name = data.values.cluster_name
#@ gitops_branch = data.values.gitops_branch
#@ globals = data.values.globals
#@ cluster = globals.clusters[cluster_name]
#@
#@ #! Ensure the current cluster is defined in global data values
#@ if cluster_name not in globals.clusters:
#@   msg = "Cluster: {} is not in global clusters. Ensure this cluster is in the globals.clusters object.".format(cluster_name)
#@   assert.fail(msg)
#@ end
#@
#@ def get_cluster_subpath():
#@   subpath = 'clusters/{}/dependent'
#@   replacement = cluster_name
#@
#@   #! if globals data value overrides the cluster subpath, use it instead of cluster_name
#@   if 'base_cluster_subpath' in cluster:
#@     replacement = cluster.base_cluster_subpath
#@   end
#@
#@   return subpath.format(replacement)
#@ end
#@
#@ def get_cluster_branch():
#@   #! Default to gitops_branch provided by cluster configmap
#@   cluster_branch = gitops_branch
#@
#@   #! Use overriden cluster_branch if supplied
#@   if 'cluster_branch' in cluster:
#@     cluster_branch = cluster.cluster_branch
#@   end
#@
#@   return cluster_branch
#@ end
#@
#! Only deploy the dependent app if there some dependent apps to install
#@ if/end 'dependent-apps' in cluster and cluster['dependent-apps']:
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: cluster-gitops-dependent
  namespace: cluster-gitops
  annotations:
    kapp.k14s.io/change-group: cluster-gitops-dependent
    kapp.k14s.io/change-rule.0: upsert after upserting cluster-gitops-base-apps
    kapp.k14s.io/change-rule.1: delete before deleting cluster-gitops-base-apps
spec:
  serviceAccountName: cluster-gitops
  paused: false
  fetch:
  #! Fetch entire kapp folder - will choose specific paths below
  - git:
      url: #@ globals.gitops.url
      ref: #@ get_cluster_branch()
      subPath: kapp
      secretRef:
        name: cluster-gitops-creds

  template:
  - sops: 
      age: 
        privateKeysSecretRef: 
          name: age-key
          
  - ytt:
      ignoreUnknownComments: true # allow regular comments with just a #

      #! specify global values path, specific path for this cluster
      #! and any dependent apps paths defined
      paths:
      - globals/values

      #! Add paths for any dependent apps defined for this cluster
      #@ if 'dependent-apps' in cluster:
      #@   for app in cluster['dependent-apps']:
      - #@ 'apps/{}'.format(app)
      #@   end
      #@ end
      
      valuesFrom:
        #! provided by configmap containing cluster values
        - configMapRef:
            name: cluster-gitops-values

  deploy:
  - kapp: {}