#@ load("@ytt:data", "data")
#@
#@ #! Store some default variables to make things cleaner below
#@ cluster_name = data.values.cluster_name
#@ gitops_branch = data.values.gitops_branch
#@ globals = data.values.globals
#@ cluster = globals.clusters[cluster_name]
#@
#@ def get_cluster_subpath():
#@   subpath = 'kapp/clusters/{}/tap-values'
#@   replacement = cluster_name
#@
#@   #! if globals data value overrides the cluster subpath, use it instead of cluster_name
#@   if 'base_cluster_subpath' in cluster:
#@     replacement = cluster.base_cluster_subpath
#@   end
#@
#@   return subpath.format(replacement)
#@ end
#@
#@ def get_cluster_branch():
#@   #! Default to gitops_branch provided by cluster configmap
#@   cluster_branch = gitops_branch
#@
#@   #! Use overriden cluster_branch if supplied
#@   if 'cluster_branch' in cluster:
#@     cluster_branch = cluster.cluster_branch
#@   end
#@
#@   return cluster_branch
#@ end
#@
#@ #! Get the tap_version for this cluster if defined, otherwise
#@ #! use the global tap_version
#@ def get_tap_version():
#@   return cluster['cluster_tap_version'] if 'cluster_tap_version' in cluster else globals.tap_version
#@ end
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  annotations:
    kapp.k14s.io/change-group: tanzu-sync
    # kapp.k14s.io/change-rule.0: upsert after upserting tanzu-sync-secrets
    # kapp.k14s.io/change-rule.1: upsert after upserting install-registry-export
    # kapp.k14s.io/change-rule.2: delete before deleting tanzu-sync-secrets
    # kapp.k14s.io/change-rule.3: delete before deleting install-registry-export
    kapp.k14s.io/change-rule.4: delete before deleting tanzu-sync-rbac
  name: sync
  namespace: cluster-gitops
spec:
  serviceAccountName: cluster-gitops

  fetch:
    #! Fetch entire kapp folder - will choose specific paths below
    - git:
        url: #@ globals.gitops.url
        ref: #@ get_cluster_branch()
        subPath: kapp
        secretRef:
          name: cluster-gitops-creds
      path: kapp

    #! provide inline files directly
    - inline:
        paths:
          #! provide the tap-install-values file, but use the 
          #! proper tap_version
          #@yaml/text-templated-strings
          tap-install-values.yaml: |
            tap_install:
              package_repository:
                oci_repository: (@= globals.tap_repo @)
              version:
                package_repo_bundle_tag: "(@= get_tap_version() @)"
                package_version: "(@= get_tap_version() @)"
      path: inline
  
  template:
    - sops:
        age:
          privateKeysSecretRef:
            name: age-key
    
    - ytt:
        paths:
        - kapp/globals/tap-configs
        valuesFrom:
        - path: #@ get_cluster_subpath()
        - path: inline

  deploy:
  - kapp: {}