#@ load("@ytt:data", "data")
---
apiVersion: authentication.concierge.pinniped.dev/v1alpha1
kind: JWTAuthenticator
metadata:
  name: pinniped-jwt-authenticator
spec:
  issuer: #@ "https://" + data.values.pinniped.supervisor.fqdn
  audience: concierge
  tls:
    certificateAuthorityDataSource:
      kind: Secret
      name: pinniped-supervisor-tls-cert
      key: ca.crt
